# Generated by Django 5.0.14 on 2026-07-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='规则书标题')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='规则书标识')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='发布状态')),
                ('source', models.CharField(blank=True, default='core', max_length=100, verbose_name='来源')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
            ],
            options={
                'verbose_name': '规则书',
                'verbose_name_plural': '规则书',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('slug', models.SlugField(max_length=220, verbose_name='章节标识')),
                ('number', models.CharField(blank=True, default='', max_length=50, verbose_name='章节号')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('source_key', models.CharField(blank=True, default='', max_length=220, verbose_name='源数据标识')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
            ],
            options={
                'verbose_name': '规则书章节',
                'verbose_name_plural': '规则书章节',
                'ordering': ['rulebook', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('block_type', models.CharField(choices=[('paragraph', '段落'), ('heading', '标题'), ('subheading', '小标题'), ('table', '表格'), ('list', '列表'), ('quote', '引用'), ('profile', '资料块'), ('stat_block', '数值块'), ('ability', '能力'), ('raw_json', '原始JSON'), ('other', '其他')], default='paragraph', max_length=50, verbose_name='内容块类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='结构化数据')),
                ('renderer_hint', models.CharField(blank=True, default='', max_length=120, verbose_name='渲染提示')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
            ],
            options={
                'verbose_name': '规则书内容块',
                'verbose_name_plural': '规则书内容块',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=220, verbose_name='条目标题')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='条目标识')),
                ('entry_type', models.CharField(choices=[('attribute', '属性'), ('race', '种族'), ('rule', '规则'), ('table', '表格'), ('other', '其他')], default='other', max_length=50, verbose_name='条目类型')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', models.TextField(blank=True, default='', verbose_name='可渲染正文')),
                ('source', models.CharField(blank=True, default='core', max_length=100, verbose_name='来源')),
                ('source_key', models.CharField(blank=True, default='', max_length=220, verbose_name='源数据标识')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
            ],
            options={
                'verbose_name': '规则书条目',
                'verbose_name_plural': '规则书条目',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='小节标题')),
                ('slug', models.SlugField(max_length=260, verbose_name='小节标识')),
                ('section_type', models.CharField(choices=[('text', '文本'), ('data', '数据'), ('group', '分组'), ('other', '其他')], default='text', max_length=50, verbose_name='小节类型')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('source_key', models.CharField(blank=True, default='', max_length=220, verbose_name='源数据标识')),
                ('data_source', models.CharField(blank=True, default='', max_length=220, verbose_name='数据源')),
                ('data_path', models.CharField(blank=True, default='', max_length=260, verbose_name='数据路径')),
                ('renderer_type', models.CharField(blank=True, default='', max_length=120, verbose_name='渲染类型')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
            ],
            options={
                'verbose_name': '规则书小节',
                'verbose_name_plural': '规则书小节',
                'ordering': ['chapter', 'sort_order', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='rule',
            new_name='rules_rule_rule_ty_92dd42_idx',
            old_name='rules_rule_rule_ty_0ca4df_idx',
        ),
        migrations.RenameIndex(
            model_name='rule',
            new_name='rules_rule_slug_3b1208_idx',
            old_name='rules_rule_slug_c9c44e_idx',
        ),
        migrations.AddField(
            model_name='rulechapter',
            name='rulebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='rules.rulebook', verbose_name='规则书'),
        ),
        migrations.AddField(
            model_name='rulecontentblock',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='rules.rulechapter', verbose_name='所属章节'),
        ),
        migrations.AddField(
            model_name='ruleentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rulebook_entries', to='rules.rulecategory', verbose_name='规则分类'),
        ),
        migrations.AddField(
            model_name='ruleentry',
            name='related_rules',
            field=models.ManyToManyField(blank=True, related_name='referenced_by', to='rules.ruleentry', verbose_name='相关规则'),
        ),
        migrations.AddField(
            model_name='rulecontentblock',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='rules.ruleentry', verbose_name='所属条目'),
        ),
        migrations.AddField(
            model_name='rulesection',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rules.rulechapter', verbose_name='所属章节'),
        ),
        migrations.AddField(
            model_name='rulesection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rules.rulesection', verbose_name='父小节'),
        ),
        migrations.AddField(
            model_name='ruleentry',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='rules.rulesection', verbose_name='所属小节'),
        ),
        migrations.AddField(
            model_name='rulecontentblock',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='rules.rulesection', verbose_name='所属小节'),
        ),
        migrations.AddIndex(
            model_name='rulechapter',
            index=models.Index(fields=['rulebook', 'sort_order'], name='rules_rulec_ruleboo_42aef6_idx'),
        ),
        migrations.AddIndex(
            model_name='rulechapter',
            index=models.Index(fields=['slug'], name='rules_rulec_slug_6d1157_idx'),
        ),
        migrations.AddIndex(
            model_name='rulechapter',
            index=models.Index(fields=['source_key'], name='rules_rulec_source__ae7db3_idx'),
        ),
        migrations.AddConstraint(
            model_name='rulechapter',
            constraint=models.UniqueConstraint(fields=('rulebook', 'slug'), name='unique_rule_chapter_slug_per_book'),
        ),
        migrations.AddIndex(
            model_name='rulesection',
            index=models.Index(fields=['chapter', 'parent', 'sort_order'], name='rules_rules_chapter_c3d69c_idx'),
        ),
        migrations.AddIndex(
            model_name='rulesection',
            index=models.Index(fields=['slug'], name='rules_rules_slug_2f498d_idx'),
        ),
        migrations.AddIndex(
            model_name='rulesection',
            index=models.Index(fields=['source_key'], name='rules_rules_source__e66873_idx'),
        ),
        migrations.AddIndex(
            model_name='rulesection',
            index=models.Index(fields=['section_type'], name='rules_rules_section_73cf0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='rulesection',
            constraint=models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_rule_section_slug_per_chapter'),
        ),
        migrations.AddIndex(
            model_name='ruleentry',
            index=models.Index(fields=['entry_type'], name='rules_rulee_entry_t_ce3ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleentry',
            index=models.Index(fields=['slug'], name='rules_rulee_slug_e73e73_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleentry',
            index=models.Index(fields=['source_key'], name='rules_rulee_source__b22815_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleentry',
            index=models.Index(fields=['section', 'sort_order'], name='rules_rulee_section_c9cc54_idx'),
        ),
        migrations.AddIndex(
            model_name='rulecontentblock',
            index=models.Index(fields=['chapter', 'sort_order'], name='rules_rulec_chapter_0833e5_idx'),
        ),
        migrations.AddIndex(
            model_name='rulecontentblock',
            index=models.Index(fields=['section', 'sort_order'], name='rules_rulec_section_3662a1_idx'),
        ),
        migrations.AddIndex(
            model_name='rulecontentblock',
            index=models.Index(fields=['entry', 'sort_order'], name='rules_rulec_entry_i_aee2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='rulecontentblock',
            index=models.Index(fields=['block_type'], name='rules_rulec_block_t_f23418_idx'),
        ),
    ]
